@SuperMegaUnboxDeluxe.Api_HostAddress = http://localhost:5077

GET {{SuperMegaUnboxDeluxe.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{SuperMegaUnboxDeluxe.Api_HostAddress}}/item/
Content-Type: text/plain
Content-Length: 0

###
