<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Persistence\Configurations\**" />
    <Compile Remove="Persistence\Outbox\**" />
    <EmbeddedResource Remove="Persistence\Configurations\**" />
    <EmbeddedResource Remove="Persistence\Outbox\**" />
    <None Remove="Persistence\Configurations\**" />
    <None Remove="Persistence\Outbox\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SuperMegaUnboxDeluxe.Application\SuperMegaUnboxDeluxe.Application.csproj" />
  </ItemGroup>

</Project>
